### ISSUE TITLE
Support Left and right switch???

### ISSUE THREAD

**Issue by devyunji** [lovels/LBTagView#1]
支持左右切换吗？？大哥

**Comment by devyunji** [comment]
![1](https://cloud.githubusercontent.com/assets/16624762/12442534/ace0c8a4-bf8b-11e5-85c8-c345a03ec51c.png)

像这样的？

**Comment by lovels** [comment]
@devyunji  暂时不支持

**Comment by lovels** [comment]
@devyunji  我近期考虑一下，然后添加上，感谢关注

**Comment by devyunji** [comment]
非常好的一个库。麻烦您完善下。其他库 写得太复杂了。还是您写的靠谱。

**Comment by lovels** [comment]
@devyunji 已支持 ，设置 `direction`属性即可，非常感谢你的支持

**Comment by devyunji** [comment]
这么快？？？真够速度。下来瞧一瞧

**Comment by devyunji** [comment]
不能点击的时候 动态切换左右？麻烦大神赐教。

**Comment by lovels** [comment]
@devyunji   你好   你可以子啊点击事件里面设置`direction`属性
