### ISSUE TITLE
How to make a relative positioning ?

### ISSUE THREAD

**Issue by dreamgo** [lovels/LBTagView#2]
Good job! It helps me a lot. Only problem is your tagView is absolutely positioning. But I need to realize relative positioning of TagView on an image view. Any idea? Thanks.

**Comment by lovels** [comment]
If you add TagView to an image view, the TagView's position is relative of the image view.Well, can you give an example?

**Comment by dreamgo** [comment]
Sorry for the confuse explain. I have a 1:1 UIImage view, which width is same with the device's.  What I need is making label always point to some object in the image(for example: a kitty) with any size of devices. I know it's not a bug, but do you have any idea to resolve it?

**Comment by dreamgo** [comment]
I have figured out the answer. Just use percentage to create the uilabel is ok. Thanks again for this nice label. Closed.

**Comment by dreamgo** [comment]
In touchesMoved function, I try to return when the label start move outside the view, but the label still can be moved.  
CGFloat leftEdge = self.center.x - self.bounds.size.width/2;
    if (left < 0) {
        NSLog(@"out left");
        return;
   }
...
